apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-certs
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  source:
    path: gitops/argocd/helm-example/apps/cert-manager
    repoURL: git@github.com:deusxanima/linkerd_cx.git
    targetRevision: HEAD
    directory:
      jsonnet: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true