apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: infra
  source:
    chart: cert-manager
    repoURL: 'https://charts.jetstack.io'
    targetRevision: v1.13.3
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: installCRDs
          value: 'true'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cert-manager