apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-crds
  namespace: linkerd
spec:
  install:
    createNamespace: false
    remediation:
      retries: -1
  interval: 1m
  chart:
    spec:
      chart: linkerd-crds
      version: "1.8.0"
      sourceRef:
        kind: HelmRepository
        name: linkerd-oss
        namespace: linkerd # This is a required value for the Linkerd control plane to use the external CA