apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: bel-examples
  path: flux/infra/cert-manager/
  prune: true