apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: argocd
  labels:
    app.kubernetes.io/instance: argocd
  namespace: argocd
resources:
  - projects/infra.yaml
  - projects/linkerd.yaml
  - apps/cert-manager.yaml
  - apps/linkerd.yaml
  - apps/linkerd-buoyant.yaml