licenseSecret: buoyant-license # NOTE: the secret needs to be named `buoyant-license` for the Linkerd control plane to automatically pull the license from the secret
linkerd-control-plane:
  identity:
    externalCA: true # This is a required value for the Linkerd control plane to use the external CA
    issuer:
      scheme: kubernetes.io/tls # This is a required value for the Linkerd control plane to automatically pull the issuer cert and key from `linkerd-identity-issuer` secret created via cert-manager

### EVERYTHING BELOW THIS LINE IS NEEDED ONLY IF USING A LICENSE SECRET NAMED SOMETHING OTHER THAN `buoyant-license`, E.G., `buoyant-custom-license` ###

    additionalEnv:
      - name: BUOYANT_LICENSE
        valueFrom:
          secretKeyRef:
            key: license
            name: buoyant-custom-license
  destinationController:
    additionalEnv:
      - name: BUOYANT_LICENSE
        valueFrom:
          secretKeyRef:
            key: license
            name: buoyant-custom-license
  heartbeat:
    additionalEnv:
      - name: BUOYANT_LICENSE
        valueFrom:
          secretKeyRef:
            key: license
            name: buoyant-custom-license
  proxyInjector:
    additionalEnv:
      - name: BUOYANT_LICENSE
        valueFrom:
          secretKeyRef:
            key: license
            name: buoyant-custom-license
  spValidator:
    additionalEnv:
      - name: BUOYANT_LICENSE
        valueFrom:
          secretKeyRef:
            key: license
            name: buoyant-custom-license