apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base  # Reference the base resources
patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: linkerd-control-plane
    patch: | 
      - op: replace
        path: /spec/source/helm/valueFiles
        value:
          - example-env-control-plane-values.yaml
