---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: linkerd-gateway-app
  labels:
    linkerd.io/extension: multicluster
rules:
- apiGroups: ["apps"]
  resources: ["replicasets"]
  verbs: ["list", "get", "watch"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["list", "get", "watch"]
- apiGroups: [""]
  resources: ["pods", "endpoints", "services"]
  verbs: ["list", "get", "watch"]
- apiGroups: ["discovery.k8s.io"]
  resources: ["endpointslices"]
  verbs: ["list", "get", "watch"]
- apiGroups: ["policy.linkerd.io"]
  resources: ["servers"]
  verbs: ["list", "get", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get"]
  resourceNames: ["linkerd-config"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: linkerd-gateway-app
  namespace: linkerd-multicluster
  labels:
    linkerd.io/extension: multicluster
---
apiVersion: v1
kind: Secret
metadata:
  name: linkerd-gateway-app-token
  namespace: linkerd-multicluster
  labels:
    linkerd.io/extension: multicluster
  annotations:
    kubernetes.io/service-account.name: linkerd-gateway-app
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: linkerd-gateway-app
  labels:
    linkerd.io/extension: multicluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: linkerd-gateway-app
subjects:
- kind: ServiceAccount
  name: linkerd-gateway-app
  namespace: linkerd-multicluster