apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-control-plane
  namespace: linkerd
spec:
  install:
    createNamespace: false
    remediation:
      retries: -1
  interval: 1m
  chart:
    spec:
      chart: linkerd-control-plane
      version: "1.16.11"
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: linkerd
  values:
    identity:
      externalCA: true
      issuer:
        scheme: kubernetes.io/tls # This is a required value for the Linkerd control plane to use the external CA