apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: linkerd
resources:
  - namespace.yaml
  - helmrepo.yaml
  - helmrelease-linkerd-crds.yaml
  - helmrelease-linkerd-control-plane.yaml
