apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: linkerd
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: flux/oss-bel-migration/linkerd/oss-linkerd-control-plane/*
  prune: true