apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-buoyant
  namespace: linkerd-buoyant
spec:
  install:
    createNamespace: false
    remediation:
      retries: -1
  interval: 1m
  chart:
    spec:
      chart: linkerd-buoyant
      version: "0.30.0"
      sourceRef:
        kind: HelmRepository
        name: linkerd-buoyant
        namespace: linkerd-buoyant
  values:
    licenseSecret: buoyant-enterprise-license
    metadata:
      agentName: bel-flux-helm-example