apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-control-plane
  namespace: argocd
  labels:
    env: example
spec:
  project: linkerd
  source:
    - repoURL: 'https://helm.buoyant.cloud'
      chart: linkerd-enterprise-control-plane
      targetRevision: 2.15.5
  destination:
    namespace: linkerd
    server: https://kubernetes.default.svc
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: linkerd-proxy-injector-k8s-tls
      jsonPointers:
        - /data/tls.crt
        - /data/tls.key
    - group: ""
      kind: Secret
      name: linkerd-sp-validator-k8s-tls
      jsonPointers:
        - /data/tls.crt
        - /data/tls.key
    - group: ""
      kind: Secret
      name: linkerd-policy-validator-k8s-tls
      jsonPointers:
        - /data/tls.crt
        - /data/tls.key
    - group: admissionregistration.k8s.io/v1
      kind: MutatingWebhookConfiguration
      name: linkerd-proxy-injector-webhook-config
      jqPathExpressions:
        - '.webhooks[0].clientConfig.caBundle'
    - group: admissionregistration.k8s.io/v1
      kind: ValidatingWebhookConfiguration
      name: linkerd-sp-validator-webhook-config
      jqPathExpressions:
        - '.webhooks[0].clientConfig.caBundle'
    - group: admissionregistration.k8s.io/v1
      kind: ValidatingWebhookConfiguration
      name: linkerd-policy-validator-webhook-config
      jqPathExpressions:
        - '.webhooks[0].clientConfig.caBundle'
