apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ns.yaml
  - base/certs/cert-manager-rbac.yaml
  - base/certs/linkerd-ca-trust-bundle.yaml
  - base/certs/linkerd-issuers-certs.yaml
  - base/linkerd-buoyant-enterprise-secret.yaml
  - base/linkerd-crds.yaml
  - base/linkerd-control-plane.yaml
patchesStrategicMerge:
  - overlays/example/patch.yaml