apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-crds
  namespace: linkerd
spec:
  install:
    createNamespace: false
    remediation:
      retries: -1
  interval: 1m
  chart:
    spec:
      chart: linkerd-enterprise-crds
      version: "2.15.2"
      sourceRef:
        kind: HelmRepository
        name: linkerd-enterprise
        namespace: linkerds # This is a required value for the Linkerd control plane to use the external CA