apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ns.yaml
  - base/linkerd-buoyant-enterprise-secret.yaml
  - base/linkerd-buoyant.yaml
  - overlays/example/dataplane-mesh-configs/*.yaml