apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-control-plane
  namespace: linkerd
spec:
  install:
    createNamespace: false
    remediation:
      retries: -1
  interval: 1m
  chart:
    spec:
      chart: linkerd-enterprise-control-plane
      version: "2.15.4"
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: linkerd
  values:
    licenseSecret: buoyant-license # NOTE: the secret needs to be named `buoyant-license` for the Linkerd control plane to automatically pull the license from the secret
    linkerd-control-plane:
      identity:
        externalCA: true # This is a required value for the Linkerd control plane to use the external CA
        issuer:
          scheme: kubernetes.io/tls # This is a required value for the Linkerd control plane to automatically pull the issuer cert and key from `linkerd-identity-issuer` secret created via cert-manager
          
### EVERYTHING BELOW THIS LINE IS NEEDED ONLY IF USING A LICENSE SECRET NAMED SOMETHING OTHER THAN `buoyant-license`, E.G., `buoyant-custom-license` ###

        additionalEnv:
          - name: BUOYANT_LICENSE
            valueFrom:
              secretKeyRef:
                key: license
                name: buoyant-enterprise-license
      destinationController:
        additionalEnv:
          - name: BUOYANT_LICENSE
            valueFrom:
              secretKeyRef:
                key: license
                name: buoyant-enterprise-license
      heartbeat:
        additionalEnv:
          - name: BUOYANT_LICENSE
            valueFrom:
              secretKeyRef:
                key: license
                name: buoyant-enterprise-license
      proxyInjector:
        additionalEnv:
          - name: BUOYANT_LICENSE
            valueFrom:
              secretKeyRef:
                key: license
                name: buoyant-enterprise-license
      spValidator:
        additionalEnv:
          - name: BUOYANT_LICENSE
            valueFrom:
              secretKeyRef:
                key: license
                name: buoyant-enterprise-license