apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: linkerd
resources:
  - namespace.yaml
  - helmrepo.yaml
  - certs/cert-manager-rbac.yaml
  - certs/linkerd-issuers-certs.yaml
  - certs/linkerd-ca-trust-bundle.yaml
  - linkerd-enterprise-secret.yaml
  - helmrelease-linkerd-crds.yaml
  - helmrelease-linkerd-control-plane.yaml
  - cert-manager-rbac.yaml
