apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: licenseSecret-patch
  namespace: linkerd
spec:
  interval: 30m
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/helm-example/apps/linkerd
  prune: true
  wait: true
  timeout: 5m0s
  patches:
    - target:
        kind: HelmRelease
        name: linkerd-control-plane
        namespace: linkerd
      patch: |-
        apiVersion: helm.toolkit.fluxcd.io/v2beta1
        kind: HelmRelease
        metadata:
          name: linkerd-control-plane
          namespace: linkerd
        spec:
          values:
            linkerd-control-plane:
              destinationController:
                additionalEnv:
                  - name: LICENSE
                    valueFrom:
                      secretKeyRef:
                        key: license
                        name: buoyant-enterprise-license
              heartbeat:
                additionalEnv:
                  - name: LICENSE
                    valueFrom:
                      secretKeyRef:
                        key: license
                        name: buoyant-enterprise-license
              identity:
                additionalEnv:
                  - name: LICENSE
                    valueFrom:
                      secretKeyRef:
                        key: license
                        name: buoyant-enterprise-license
              proxyInjector:
                additionalEnv:
                  - name: LICENSE
                    valueFrom:
                      secretKeyRef:
                        key: license
                        name: buoyant-enterprise-license
              spValidator:
                additionalEnv:
                  - name: LICENSE
                    valueFrom:
                      secretKeyRef:
                        key: license
                        name: buoyant-enterprise-license
