apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: linkerd-trust-root-issuer
  namespace: cert-manager
spec:
  selfSigned: {}
---
# Linkerd trust root certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-identity-trust-anchor
  namespace: linkerd
spec:
  commonName: root.linkerd.cluster.local
  isCA: true
  duration: 87600h0m0s
  renewBefore: 87264h0m0s
  issuerRef:
    name: linkerd-trust-root-issuer
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA
  secretName: linkerd-identity-trust-anchor
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "cert-manager,linkerd"  # Control destination namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true" # Auto create reflection for matching namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "cert-manager,linkerd" # Control auto-reflection namespaces
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: linkerd-identity-issuer
  namespace: linkerd
spec:
  ca:
    secretName: linkerd-identity-trust-anchor
---
# Linkerd identity issuer certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-identity-issuer
  namespace: linkerd
spec:
  commonName: identity.linkerd.cluster.local
  isCA: true
  usages:
  - cert sign
  - crl sign
  - server auth
  - client auth
  duration: 168h0m0s
  renewBefore: 72h0m0s
  issuerRef:
    name: linkerd-identity-issuer
    kind: Issuer
  privateKey:
    algorithm: ECDSA
  secretName: linkerd-identity-issuer